@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.storage.loot.conditions;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;