image: openjdk:8-jdk

stages:
- setup
- test
- build
- publish

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
- export GRADLE_USER_HOME=`pwd`/.gradle
- git submodule sync --recursive
- git submodule update --init --recursive

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches

setup:
  stage: setup
  script:
  - chmod +x gradlew && ./gradlew setup
  - mv src/main/java/org* projects/Kettle/src/main/java

test:
  stage: test
  script:
  - chmod +x gradlew && ./gradlew check

build:
  stage: build
  script:
  - chmod +x gradlew && ./gradlew build
  only:
  - master
  artifacts:
    paths:
      - build/distributions/*.jar

publish:
  stage: publish
  script:
  - chmod +x gradlew && ./gradlew githubRelease

after_script:
- echo "End CI"
