image: openjdk:8-jdk

stages:
- test
- build

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
- export GRADLE_USER_HOME=`pwd`/.gradle
- git submodule sync --recursive
- git submodule update --init --recursive

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches

build:
  stage: build
  script:
  - mv src/main/java/org* projects/Kettle/src/main/java
  - chmod +x gradlew && ./gradlew build
  only:
  - master
  artifacts:
    paths:
      - build/distributions/*.jar
  
test:
  stage: test
  script:
  - chmod +x gradlew && ./gradlew check

after_script:
- echo "End CI"
