#!/usr/bin/env bash

# resolve shell-specifics
case "$(echo "$SHELL" | sed -E 's|/usr(/local)?||g')" in
    "/bin/zsh")
        RCPATH="$HOME/.zshrc"
        SOURCE="${BASH_SOURCE[0]:-${(%):-%N}}"
    ;;
    *)
        RCPATH="$HOME/.bashrc"
        if [[ -f "$HOME/.bash_aliases" ]]; then
            RCPATH="$HOME/.bash_aliases"
        fi
        SOURCE="${BASH_SOURCE[0]}"
    ;;
esac

# get base dir regardless of execution location
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ "$SOURCE" != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SOURCE=$([[ "$SOURCE" = /* ]] && echo "$SOURCE" || echo "$PWD/${SOURCE#./}")
basedir=$(dirname "$SOURCE")
gitcmd="git -c commit.gpgsign=false"

source "$basedir/scripts/functions.sh"

failed=0
case "$1" in
    "p" | "patch")
    (
        set -e
        cd "$basedir"
        scripts/build.sh "$basedir" || exit 1
    ) || failed=1
    ;;
    "j" | "jar")
    (
        set -e
        cd "$basedir"
        scripts/build.sh "$basedir" "--jar" || exit 1
    ) || failed=1
    ;;
    "make")
    (
        if [[ "$2" = "bacon" ]] ; then
            set -e
            cd "$basedir"
            scripts/build.sh "$basedir" "--jar"
        fi
    )
    ;;
    "m" | "mcdev")
    (
        set -e
        cd "$basedir"
        scripts/makemcdevsrc.sh "$basedir"
    )
    ;;
    "t" | "test" | "testserver")
    (
        cd "$basedir"
        shift
        scripts/testServer.sh "$basedir" "$@"
    )
    ;;
    "td" | "testdir")
        cd "${KETTLE_TEST_DIR:-$basedir/work/test-server}"
    ;;
    "u" | "up" | "upstream")
    (
        cd "$basedir"
        scripts/upstreamMerge.sh "$basedir" "$2"
    )
    ;;
    "cu" | "commitup" | "commitupstream" | "upc" | "upcommit" | "upstreamcommit")
    (
        cd "$basedir"
        shift
        scripts/upstreamCommit.sh "$@"
    )
    ;;
    "r" | "root")
        cd "$basedir"
    ;;
    "c" | "clean")
    # Modify this to work with kettle build dirs
        rm examplefileordir
        echo "Cleaned build files"
    ;;
    "setup")
        if [[ -f "$RCPATH" ]] ; then
            NAME="kettle"
            if [[ ! -z "${2+x}" ]] ; then
                NAME="$2"
            fi
            (grep "alias $NAME=" "$RCPATH" > /dev/null) && (sed -i "s|alias $NAME=.*|alias $NAME='. $SOURCE'|g" "$RCPATH") || (echo "alias $NAME='. $SOURCE'" >> "$RCPATH")
            alias "$NAME=. $SOURCE"
            echo "You can now just type '$NAME' at any time to access the kettle tool."
        else
          echo "We were unable to setup the kettle build tool alias: $RCPATH is missing"
        fi
    ;;
    *)
        echo "Kettle build tool command. This provides a variety of commands to build and manage Kettle building"
        echo "environment. For all of the functionality of this command to be available, you must first run the"
        echo "'setup' command. View below for details. For essential building and patching, you do not need to do the setup."
        echo "This file and the scripts that it uses are taken and modified from PaperMC/Paper"
        echo ""
        echo " Normal commands:"
        echo "  * p, patch          | Apply all patches to the project without building it. Can be run from anywhere."
        echo "  * j, jar            | Apply all patches and build the project, kettle.jar will be output. Can be run from anywhere."
        echo "  * m, mcdev          | Setup decompiled sources for non-modified NMS files to be imported into an IDE. Can be run from anywhere."
        echo "  * u, up, upstream   | Updates the submodules used by Kettle to their latest upstream versions."
        echo "  * t, testserver     | Run the test server with the set of plugins and mode Kettle uses as a basis for server tests."
        echo ""
        echo " These commands require the setup command before use:"
        echo "  * r, root           | Change directory to the root of the project."
        echo "  * td, testdirectory | Move to the test-server directory."
        echo ""
        echo "  * setup             | Add an alias to $RCPATH to allow full functionality of this script. Run as:"
        echo "                      |     . ./kettle setup"
        echo "                      | After you run this command you'll be able to just run 'kettle' from anywhere."
        echo "                      | The default name for the resulting alias is 'kettle', you can give an argument to override"
        echo "                      | this default, such as:"
        echo "                      |     . ./kettle setup example"
        echo "                      | Which will allow you to run 'example' instead."
    ;;
esac

unset RCPATH
unset SOURCE
unset basedir
unset -f color
unset -f colorend
unset -f kettlestash
unset -f kettleunstash
if [[ "$failed" == "1" ]]; then
	unset failed
	false
else
	unset failed
	true
fi
