@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.status.client;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;