@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.multiplayer;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;