@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.storage.loot;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;